### ISSUE TITLE
Failed to connect to localhost port 9515: Connection refused

### ISSUE THREAD

**Issue by lukasleitsch** [chilio/laravel-dusk-ci#14]
Thanks a lot for the docker image. It helps me to setup the testing stage on the GitLab server.

In the last times I have random failure and I find no reason why. Clear the GitLab Runner Cache helps sometimes.

That is the output of the job for all tests:

```
1) Tests\Browser\LogsTest::testAdmin
Facebook\WebDriver\Exception\WebDriverCurlException: Curl error thrown for http POST to /session with params: {"desiredCapabilities":{"browserName":"chrome","platform":"ANY","chromeOptions":{"binary":"","args":["--disable-gpu","--headless","--no-sandbox"]}}}

Failed to connect to localhost port 9515: Connection refused

/builds/project/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php:286
/builds/project/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php:126
/builds/project/tests/DuskTestCase.php:40
/builds/project/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:189
/builds/project/vendor/laravel/framework/src/Illuminate/Support/helpers.php:770
/builds/project/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:190
/builds/project/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:92
/builds/project/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:64
/builds/project/tests/Browser/LogsTest.php:27
```

The relevent part of the `.gitlab-ci.yml`

```
cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    #- node_modules/
    - .npm
    - vendor/
    - public/css/
    - public/js/
    - public/fonts/
    - public/mix-manifest.json

variables:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER: homestead
  MYSQL_PASSWORD: secret
  MYSQL_DATABASE: homestead
  DB_HOST: mariadb
  DB_CONNECTION: mysql
  SCREEN_RESOLUTION: 1920x1080x24
  
before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - mkdir -p ~/.ssh
  - eval $(ssh-agent -s)
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

stages:
  - build_npm
  - build_composer
  - test
  - deploy
  - release

build_npm:
  stage: build_npm
  image: node:8
  script:
    - npm config set cache $(pwd)/.npm --global
    - npm i npm -g
    - npm -v
    - npm ci
    - npm run production

build_composer:
  stage: build_composer
  image: composer
  script:
    - cp .env.testing .env
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts

test:
  stage: test
  image: chilio/laravel-dusk-ci
  services:
      - mariadb
  script:
    - cp .env.testing .env
    - configure-laravel
    - start-nginx-ci-project
    - chown -R www-data storage/framework
    - php artisan dusk --colors --debug
  artifacts:
    paths:
      - ./storage/logs # for debugging
      - ./tests/Browser/screenshots
      - ./tests/Browser/console
    expire_in: 7 days
    when: always
```

What information do you need to investigate this issue?
