### ISSUE TITLE
php_network_getaddresses Name or service not know

### ISSUE THREAD

**Issue by chinleung** [chilio/laravel-dusk-ci#21]
I've taken the files from the example and it keeps giving me this:

```
SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name o  
  r service not known
```

Here's the .gitlab-ci

```
stages:
  - build
  - test

# Variables
variables:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER: root
  MYSQL_PASSWORD: secret
  MYSQL_DATABASE: test
  DB_HOST: mysql
  DB_CONNECTION: mysql

build:
  stage: build
  services:
     - mysql:5.7

  image: chilio/laravel-dusk-ci:stable
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    # - npm install # if you need to install additional modules from your projects package.json
    # - npm run dev # if you need to run dev scripts for example laravel mix 
  cache:
      key: ${CI_BUILD_REF_NAME}
      paths:
        # these are only examples, you should modify them according to your project, 
        # or remove cache routines entirely, if they are causing any problems on your next builds..
        # below are 2 safe ones if you use composer install and npm install in your stage script
        - vendor
        - node_modules
         # - /resources/assets/vendors  # for example if you put your vendor node-libraries there

test:
  stage: test
  cache:
    key: ${CI_BUILD_REF_NAME}
    paths:
      - vendor
      - node_modules
    policy: pull
    
  services:
    - mysql:5.7

  image: chilio/laravel-dusk-ci:stable
  script:
    - cp .env.example .env
    # - cp phpunit.xml.ci phpunit.xml # if you are using custom config for your phpunit tests in CI
    - configure-laravel
    - start-nginx-ci-project
    - ./vendor/phpunit/phpunit/phpunit -v --coverage-text --colors --stderr
    # - phpunit -v --coverage-text --colors --stderr # if you want to use preinstalled phpunit
    - php artisan dusk --colors --debug

  artifacts:
    paths:
      - ./storage/logs # for debugging
      - ./tests/Browser/screenshots
      - ./tests/Browser/console
    expire_in: 7 days
    when: always
```

And my .env.example:

```
APP_NAME="Testing"
APP_ENV=testing
APP_DEBUG=true
APP_URL=http://localhost
APP_KEY=

DB_HOST=mysql
DB_DATABASE=test
DB_USERNAME=root
DB_PASSWORD=secret

CACHE_DRIVER=array
SESSION_DRIVER=array
QUEUE_DRIVER=sync
MAIL_DRIVER=log
```

**Comment by chilio** [comment]
@chinleung what versions of gitlab, docker and gitlab-runner are you using?
After which command the error is displayed?
It seems like some problem with underlying docker, cause it means that testing image could not connect to mysql docker instance. 
Is mysql properly downloaded and started in gitlab pipeline logs?

**Comment by chinleung** [comment]
@chilio I see in the pipeline logs the following:

```
Using Docker executor with image chilio/laravel-dusk-ci:stable ...
Starting service mysql:5.7 ...
Pulling docker image mysql:5.7 ...
Using docker image mysql:5.7 ID=sha256:66bc0f66b7af6ba3ea96582685d3afcd6dff93c2f8999da0ffadd67b280db548 for mysql service...
Waiting for services to be up and running...

*** WARNING: Service runner-689f83b9-project-23-concurrent-0-mysql-0 probably didn't start properly.
```

**Comment by chilio** [comment]
@chinleung Your problem is in this line:
`*** WARNING: Service runner-689f83b9-project-23-concurrent-0-mysql-0 probably didn't start properly.`
Which means that docker has problem running mysql instance.
Therefore throwed error: `SQLSTATE[HY000] [2002] php_network_getaddresses:` makes sense.

There could be several problems, but for sure you need to check your docker installation (sometimes it can be something as silly as low space, mem, etc.)

First I would try to run mysql manually and make sure it works... [Some more info here...](https://hub.docker.com/_/mysql/)

**Comment by chinleung** [comment]
@chilio Yeah that's what I thought too. Thanks I'll have a look on why it's not starting properly. I'll post back here once I find the solution for anyone with the same issue.

**Comment by chilio** [comment]
@chinleung did you succeeded with this issue?

**Comment by chinleung** [comment]
@chilio No I am still working on it. I've tried multiple things like these guides:

- https://docs.gitlab.com/runner/register/index.html#docker
- https://docs.gitlab.com/runner/install/docker.html

I've also tried to enable the `privileged` to the docker container but I'm still unable to start the SQL service.

```
Using Docker executor with image chilio/laravel-dusk-ci:stable ...
Starting service mysql:5.7 ...
Pulling docker image mysql:5.7 ...
Using docker image sha256:66bc0f66b7af6ba3ea96582685d3afcd6dff93c2f8999da0ffadd67b280db548 for mysql:5.7 ...
Waiting for services to be up and running...

*** WARNING: Service runner-237f18d2-project-23-concurrent-0-mysql-0 probably didn't start properly.

Health check error:
ContainerStart: Error response from daemon: Cannot link to a non running container: /runner-237f18d2-project-23-concurrent-0-mysql-0 AS /runner-237f18d2-project-23-concurrent-0-mysql-0-wait-for-service/service

Service container logs:
2018-07-11T19:49:03.214991318Z 
2018-07-11T19:49:03.215062485Z ERROR: mysqld failed while attempting to check config
2018-07-11T19:49:03.215067480Z command was: "mysqld --verbose --help"
2018-07-11T19:49:03.215070774Z 
2018-07-11T19:49:03.215073778Z mysqld: error while loading shared libraries: libpthread.so.0: cannot stat shared object: Permission denied
```

**Comment by chinleung** [comment]
@chilio I think that's the issue, I'm not able to run mysql properly with docker but I can't figure out why... Any ideas?

**Comment by chilio** [comment]
@chinleung I've never tried it, but I have seen that others had some problems with it...

**Comment by Raccoon5031** [comment]
@chinleung By using `services: -mysql:5.7`. This kind of structure is automatically created

![image](https://user-images.githubusercontent.com/22834507/42989760-16ef28a0-8c01-11e8-8218-c72059f9c0de.png)

So everything is a docker container and you don't have to manage your mysql VM/container or even the service on your host by yourself.

By using

```
variables:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER: root
  MYSQL_PASSWORD: secret
  MYSQL_DATABASE: test
  DB_HOST: mysql
  DB_CONNECTION: mysql
```

The database is already created with the credentials and @chilio made a little script to make your life easier by using

```
script:
    - configure-laravel
```

Your laravel env will be setup and your database will be created and seeded (Idon't know if this word exist)

You can have a look [here ](https://github.com/chilio/laravel-dusk-ci/blob/master/commands/configure-laravel.sh)to see what this command is really doing.

I hope it will help you to debug or at least to have a better understanding of the workflow.
