### ISSUE TITLE
Ability to remove xdebug ?

### ISSUE THREAD

**Issue by quienti** [chilio/laravel-dusk-ci#23]
Hi,

I try to remove xdebug without success.
Because with xdebug, my tests run very slow

Before your docker: ~20 minutes
With your docker: ~1 hour and 10 minutes

But nothing working...

Thank you in advance for your help

My .gitlab-ci.yml
```
stages:
  - build
  - test

variables:
  MYSQL_DATABASE: project_name
  MYSQL_ROOT_PASSWORD: secret

build:
  stage: build
  services:
    - mysql:5.7

  image: chilio/laravel-dusk-ci:stable
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts

    # Install Node dependencies.
    - npm install

    # Install jshint
    - npm install -g jshint

    # Run npm build
    - npm run dev

    # Remove php-xdebug
    - phpdismod -s cli xdebug
    - phpdismod xdebug

  cache:
    key: ${CI_BUILD_REF_NAME}
    paths:
      - vendor
      - node_modules
      - public

test:
  stage: test
  cache:
    key: ${CI_BUILD_REF_NAME}
    paths:
      - vendor
      - node_modules
      - public
    policy: pull

  services:
    - mysql:5.7

  image: chilio/laravel-dusk-ci:stable
  script:
  - composer update --no-scripts  

  # Copy over testing configuration.
  - cp .env.ci.testing .env

  # Generate an application key. Re-cache.
  - php artisan config:cache
  - chmod -R 775 storage
  - chmod 775 bootstrap/cache
  - chown -R www-data ./
  - php artisan key:generate

  # Command to check chrome lib
  - chrome-system-check
  - sleep 10s

  # Command to start nginx
  - start-nginx-ci-project

  # Run database migrations.
  - php artisan module:migrate

  # Run database seed
  - php artisan module:seed

  # run laravel tests
  - php vendor/bin/phpunit --no-coverage --colors=never --printer=Codedungeon\\PHPUnitPrettyResultPrinter\\Printer

  # run frontend tests
  - npm test

  # run phpcs
  - ./vendor/bin/phpcs -p --error-severity=1 --warning-severity=8 --extensions=php

  # run jshint
  - jshint --show-non-errors public/js/modules/.

  artifacts:
    paths:
      - ./storage/logs # for debugging
      - ./tests/Browser/console # for debugging
      - ./tests/Browser/screenshots # for debugging
    expire_in: 7 days
    when: always

```

**Comment by quienti** [comment]
Never mind, so stupid ^^

I have just remove php-xdedub in my 'test' stage

```
stages:
  - build
  - test

variables:
  MYSQL_DATABASE: project_name
  MYSQL_ROOT_PASSWORD: secret

build:
  stage: build
  services:
    - mysql:5.7

  image: chilio/laravel-dusk-ci:stable
  script:
    # Install composer
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts

    # Install Node dependencies.
    - npm install

    # Install jshint
    - npm install -g jshint

    # Run npm build
    - npm run dev

  cache:
    key: ${CI_BUILD_REF_NAME}
    paths:
      - vendor
      - node_modules
      - public

test:
  stage: test
  cache:
    key: ${CI_BUILD_REF_NAME}
    paths:
      - vendor
      - node_modules
      - public
    policy: pull

  services:
    - mysql:5.7

  image: chilio/laravel-dusk-ci:stable
  script:
  # Remove php-xdebug
  - apt-get purge php-xdebug -y

  # Update composer
  - composer update --no-scripts  

  # Copy over testing configuration.
  - cp .env.ci.testing .env

  # Generate an application key. Re-cache.
  - php artisan config:cache
  - chmod -R 775 storage
  - chmod 775 bootstrap/cache
  - chown -R www-data ./
  - php artisan key:generate

  # Command to check chrome lib
  - chrome-system-check
  - sleep 10s

  # Command to start nginx
  - start-nginx-ci-project

  # Run database migrations.
  - php artisan module:migrate

  # Run database seed
  - php artisan module:seed

  # run laravel tests
  - php vendor/bin/phpunit --no-coverage --colors=never --printer=Codedungeon\\PHPUnitPrettyResultPrinter\\Printer

  # run frontend tests
  - npm test

  # run phpcs
  - ./vendor/bin/phpcs -p --error-severity=1 --warning-severity=8 --extensions=php

  # run jshint
  - jshint --show-non-errors public/js/modules/.

  artifacts:
    paths:
      - ./storage/logs # for debugging
      - ./tests/Browser/console # for debugging
      - ./tests/Browser/screenshots # for debugging
    expire_in: 7 days
    when: always
```
