### ISSUE TITLE
Dusk result give a false positive

### ISSUE THREAD

**Issue by Gil-1** [chilio/laravel-dusk-ci#53]
I'm currently working on a full pipe check based of ohdear's config (https://github.com/ohdearapp/gitlab-ci-pipeline-for-laravel)
I added a dusk part using this docker image and if the tests fails I still have Gitlab telling me it succeded.

You can check the dusk job config here :
```
dusk:
  stage: testing
  image: chilio/laravel-dusk-ci
  services:
    - name: mysql:8.0
      command: ["--default-authentication-plugin=mysql_native_password"]
  dependencies:
    - build-assets
    - composer
    - db-seeding
  script:
    - php -v
    - mysql --host="${DB_HOST}" --user="${MYSQL_USER}" --password="${MYSQL_PASSWORD}" "${MYSQL_DATABASE}" < db.sql
    - google-chrome --version
    # Upgrade Chrome Driver
    - php artisan dusk:chrome-driver 77
    - start-nginx-ci-project
    # Run Dusk Tests
    - php artisan dusk --colors --debug
  artifacts:
    paths:
      - storage/logs # for debugging
      - tests/Browser/screenshots
      - tests/Browser/console
    expire_in: 1 days
    when: always
```

And here is what I get as an output if I make it fail
```

ERRORS!
Tests: 41, Assertions: 0, Errors: 41.
Uploading artifacts...
storage/logs: found 2 matching files               
tests/Browser/screenshots: found 2 matching files  
tests/Browser/console: found 2 matching files      
Uploading artifacts to coordinator... ok            id=338202026 responseStatus=201 Created token=6t_BaFoR
Job succeeded
```

Any idea where it could come from ?
