### ISSUE TITLE
Laravel 11 & PHP 8.4

### ISSUE THREAD

**Issue by cwbsl** [chilio/laravel-dusk-ci#80]
Hi there

First of all thanks for this library, even though I wasn't able to get it to work properly for my case yet. I have the following setup:
- Laravel 11
- PHP 8.4

And this is my .gitlab-ci.yml file:

```
browser:
  stage: test
  tags:
    - ubuntu
  cache:
    key: ${CI_BUILD_REF_NAME}
    paths:
      - vendor
      - node_modules
    policy: pull
  services:
    - name: mysql:8.4
      alias: mysql-test
  image: chilio/laravel-dusk-ci:php-8.4
  variables:
    APP_ENV: local
    APP_DEBUG: true
    APP_URL: http://localhost:8000
    DB_HOST: mysql
    MYSQL_ROOT_PASSWORD: MyVerySecretPassword!
    MYSQL_DATABASE: mydatabasename
    MYSQL_PASSWORD: MyVerySecretPassword!
  script:
    - php artisan dusk:install
    - configure-laravel
    - start-nginx-ci-project
    - php artisan migrate --force
    - php artisan db:seed --class=DatabaseSeeder
    - php artisan dusk --colors --debug
  artifacts:
    paths:
      - ./storage/logs # for debugging
      - ./tests/Browser/screenshots
      - ./tests/Browser/console
    expire_in: 7 days
    when: always
```

And here is the output I get:

![Image](https://github.com/user-attachments/assets/1c48fe94-3e4f-4f7b-8da2-e257322486ff)

After that it just loops and times out after 1 hour.

What am I doing wrong?
